server {
    listen 80;

    location /api/v1/ventas {
        proxy_pass http://backend-service/api/v1/ventas;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/v1/despachos {
        proxy_pass http://backend-despachos-service/api/v1/despachos;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
